=== davidko-git/PingAndLog/PingAndLog/PingResultsSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="TargetAddress" type="xs:string"/>
    <xs:element name="Status" type="xs:string"/>
    <xs:element name="RoundtripTime" type="xs:string"/>

    <xs:element name="PingReplyRecord">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TargetAddress" minOccurs ="0"/>
                <xs:element ref="Status" minOccurs="0"/>
                <xs:element ref="RoundtripTime" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Results">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="PingReplyRecord" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== davidko-git/PingAndLog/PingAndLog/bin/Release/net5.0/output.xml
<?xml version="1.0" encoding="UTF-8" ?><Results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PingResultsSchema.xsd">
<PingReplyRecord><TargetAddress>127.0.0.1</TargetAddress><Status>Success</Status><RoundtripTime>0</RoundtripTime></PingReplyRecord><PingReplyRecord><TargetAddress>192.168.0.1</TargetAddress><Status>Success</Status><RoundtripTime>4</RoundtripTime></PingReplyRecord><PingReplyRecord><TargetAddress>128.0.0.1</TargetAddress><Status>TimedOut</Status><RoundtripTime>0</RoundtripTime></PingReplyRecord><PingReplyRecord><TargetAddress>192.168.0.2</TargetAddress><Status>TimedOut</Status><RoundtripTime>0</RoundtripTime></PingReplyRecord><PingReplyRecord><TargetAddress>192.168.0.3</TargetAddress><Status>TimedOut</Status><RoundtripTime>0</RoundtripTime></PingReplyRecord></Results>
